[package]
name = "protostar"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
dirs = "4.0.0"
ez-pixmap = "0.2.2"
glam = { version = "0.22.0", features = ["mint"] }
image = "0.24.5"
manifest-dir-macros = "0.1.16"
mint = "0.5.9"
nix = "0.26.1"
resvg = "0.28.0"
rustc-hash = "1.1.0"
stardust-xr-molecules = "0.8.0"
tokio = { version = "1.22.0", features = ["full"] }
tween = "1.0.1"
ustr = "0.9.0"
walkdir = "2.3.2"

[dev-dependencies]
tempdir = "0.3.7"
